server {
    listen 80;
    server_name _; # Hoặc IP của VPS sau này

    # Cấu hình lưu log
    access_log /home/YOUR_USER/Projects/QuickOrder/server/logs/nginx_access.log;
    error_log /home/YOUR_USER/Projects/QuickOrder/server/logs/nginx_error.log;

    # 1. Phục vụ ảnh món ăn (Nginx xử lý cực nhanh)
    location /static/ {
        alias /home/YOUR_USER/Projects/QuickOrder/server/apps/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 2. Đẩy yêu cầu API cho Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/home/YOUR_USER/Projects/QuickOrder/server/quickorder.sock;

        # Hỗ trợ timeout lâu cho các xử lý nặng
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }

    # Cho phép upload ảnh lên tới 10MB
    client_max_body_size 10M;
}